[Module] Cloudflare
dbl-works/terraform pull request #75
Opened 2022-05-26 09:50 UTC by samkahchiin

### Summary
This module done the following:

- Domain validation
  - Configure a CNAME record in DNS configuration to establish control of your domain name. This allows ACM to automatically renew DNS-validated certificates before they expire, as long as the DNS record has not changed
- Route to defaults routes
    - api.my-project.com to the NLB
    - bastion.my-project.com
    - cdn.my-project.com to the S3-Bucket (using Cloudflare Workers)
    - xx.my-project.com to the S3-Bucket (using Cloudflare Workers) for any subdomain needed

2022-06-10 18:28 UTC, swiknaba commented on cloudflare/README.md
> +2. Make sure you have create API token in your cloudflare account with sufficient permissions
```suggestion
2. Make sure you have created an API token in your Cloudflare account with sufficient permissions
```

2022-06-10 18:29 UTC, swiknaba commented on cloudflare/README.md
> +  s3_cdn_buckets = [
```suggestion
  s3_public_buckets = [
```

we've renamed the "cdn" bucket module into "public" to be more general. should we do the same here?

2022-06-10 18:34 UTC, swiknaba commented on cloudflare/main.tf
> +resource "cloudflare_record" "bastion" {
should we make this optional, e.g. by skipping this resource, if `bastion_public_dns` is not given?

2022-06-13 19:09 UTC, swiknaba requested changes
pls have a look 🙂 

https://github.com/dbl-works/terraform/pull/87
https://github.com/dbl-works/terraform/runs/6867926154?check_suite_focus=true

<img width="930" alt="image" src="https://user-images.githubusercontent.com/20702503/173426991-8d0612dd-746d-4e05-b997-b8e6a8023c06.png">

2022-06-14 03:13 UTC, samkahchiin commented
@swiknaba 
Have fixed accordingly. 
Just realised that the domain_validation_options is not available in data source (Only available in resources).  😢

2022-06-21 05:58 UTC, closed without merging